#!/usr/bin/python3 -O

# The Qubes OS Project, http://www.qubes-os.org
#
# Copyright (C) 2013  Wojciech Porczyk <wojciech@porczyk.eu>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

import argparse
import qubesadmin
import qubesimgconverter
import sys

# Maximum --allow-highres supported uncompressed image size =~ 15.6GB
HIGHRES_WIDTH = 64000
HIGHRES_HEIGHT = 64000

parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter,
        description='Secure copy of images between virtual machines',
        epilog='To allow image sizes over 1GB with --allow-highres option,'
        'increase "/tmp" allocated free space in Source VM.\n'
        'Both SRC and DST may specify format in gm(1) way,\n'
        'i.e. png:aqq.gif\n')

parser.add_argument('vmname', metavar='VMNAME', help='Source VM')
parser.add_argument('src', metavar='SRC', help='Path inside source VM')
parser.add_argument('dst', metavar='DST', help='Destination path in this VM')
parser.add_argument('--allow-highres', action='store_true',
        help=f'Allow pictures up to {HIGHRES_WIDTH}x{HIGHRES_HEIGHT} pixels')

def main():
    args = parser.parse_args()

    app = qubesadmin.Qubes()
    try:
        vm = app.domains[args.vmname]
    except KeyError:
        vm = None

    if vm is None:
        parser.error('No such VM: {0}'.format(args.vmname))

    kwargs = {}
    if args.allow_highres:
        kwargs = {'max_width': HIGHRES_WIDTH, 'max_height': HIGHRES_HEIGHT}

    try:
        qubesimgconverter.Image.get_from_vm(
                        vm, args.src, **kwargs).save(args.dst)
    except ValueError as e:
        app.log.error(e)
        return 1

    return 0
if __name__ == '__main__':
    sys.exit(main())

# vim: ft=python sw=4 ts=4 et
