#!/bin/bash

set -e

if [[ $# -ne 2 ]] && [[ $# -ne 3 || "$3" != "--allow-highres" ]]; then
        echo usage: $0 '<img to convert> <location converted file> [--allow-highres]'
        exit 1
fi

if [ ! -f "$1" ] ; then
        echo "image file does not exists: $1"
        exit 1
fi

exec /usr/lib/qubes/qrexec-client-vm '@dispvm' qubes.GetImageRGBA \
	/usr/lib/qubes/qimg-convert-client "$@"
