#!/bin/sh

set -e

if [ $# -ne 2 ] ; then
        echo usage: $0 '<img to convert> <location converted file>'
        exit 1
fi

exec /usr/lib/qubes/qrexec-client-vm '$dispvm' qubes.GetImageRGBA \
	/usr/lib/qubes/qimg-convert-client "$@"
